#!/bin/bash

cd "$(dirname $0)/src/shaders"

SOURCES="quad.vert quad.frag"
OUT_HEADER="shaders_gen.h"

echo '#pragma once' > $OUT_HEADER
echo "// Generated by $(basename $0) at $(date --iso-8601=seconds)" >> $OUT_HEADER
echo '#include <stdint.h>' >> $OUT_HEADER

for SRC in $SOURCES; do
	VARNAME="shader_code_${SRC//./_}"
	glslc -O "$SRC" -o - \
		| xxd -i -n "$VARNAME" \
		| sed 's/^unsigned char /const uint8_t /' \
		| sed 's/^unsigned int /const int /' \
	    >> $OUT_HEADER
done
