#!/bin/bash

set -e
cd "$(dirname $0)"

SHADER_DIR="src/shaders"
SHADER_SOURCES="quad.vert quad.frag"
SHADER_OUT_HEADER="$SHADER_DIR/shaders_gen.h"

echo '#pragma once' > $SHADER_OUT_HEADER
echo "// Generated by $(basename $0) at $(date --iso-8601=seconds)" >> $SHADER_OUT_HEADER
echo '#include <stdint.h>' >> $SHADER_OUT_HEADER

for SRC in $SHADER_SOURCES; do
	SPV="build/$SRC.spv"
	VARNAME="shader_code_${SRC//./_}"
	glslc -O "$SHADER_DIR/$SRC" -o "$SPV"
	xxd -i -n "$VARNAME" "$SPV" \
		| sed 's/^unsigned char /const uint8_t /' \
		| sed 's/^unsigned int /const int /' \
	    >> $SHADER_OUT_HEADER
done

mkdir -p build
SDL_OUT="$(pwd)/vendor/SDL/build"

clang src/main.c \
	-std=gnu23 \
	-Ivendor/include \
	-Ivendor/SDL/include \
	-Wall -Wpedantic -Wextra \
	-ggdb -Og \
	-lm "$SDL_OUT/libSDL3.so" -Wl,-rpath,"$SDL_OUT" \
	-o build/pf2
